### ISSUE TITLE
[Question] 训练营rcore tutorial和rustlings视频讲解 没有提供密码

### ISSUE THREAD

**Issue by dicsh** [LearningOS/rust-based-os-comp2022#100]
https://github.com/LearningOS/rust-based-os-comp2022/blob/main/relatedinfo.md#%E8%AE%AD%E7%BB%83%E8%90%A5rcore-tutorial%E5%92%8Crustlings%E8%A7%86%E9%A2%91%E8%AE%B2%E8%A7%A3
请问这里视频的密码是什么？

**Comment by Godones** [comment]
xushanpu123
