### ISSUE TITLE
姓名: 卢雪馨

### ISSUE THREAD

**Issue by TihayaKousaka** [LearningOS/rust-based-os-comp2022#110]
姓名: 卢雪馨
单位: 香港中文大学
电邮: lixiaoxiao804@163.com
微信id: 
github id: TihayaKousaka
个人目标: 学习操作系统制作，Rust以及操作系统网络设置

_Originally posted by @Comet959 in https://github.com/LearningOS/rust-based-os-comp2022/issues/101#issuecomment-1279963079_

**Comment by YdrMaster** [comment]
#101
