### ISSUE TITLE
2022秋冬季开元操作系统训练营报名: 江成

### ISSUE THREAD

**Issue by GopherJ** [LearningOS/rust-based-os-comp2022#113]
姓名: 江成
单位: 美国某区块链公司
电邮: [alex_cj96@foxmail.com](mailto:alex_cj96@foxmail.com)
微信id: jc13125335
github id: GopherJ
个人目标: Rust, Solidity，区块链底层，DEFI, 期望本次能够学习了解操作系统底层知识

_Originally posted by @GopherJ in https://github.com/LearningOS/rust-based-os-comp2022/issues/101#issuecomment-1283211164_

**Comment by YdrMaster** [comment]
#101
