### ISSUE TITLE
[Bug] 标题示例: 自动安装配置开发环境失败

### ISSUE THREAD

**Issue by allenli178** [LearningOS/rust-based-os-comp2022#133]
使用新建codespace环境时，直接运行 `sudo make codespaces_setenv`会失败。需要更新一下软件源再运行自动配置环境的脚本。

![image](https://user-images.githubusercontent.com/53218750/198820547-bdfce51b-2692-4a0e-96e6-35ef61bb3d0a.png)

**Comment by YdrMaster** [comment]
好的
