### ISSUE TITLE
[Feature] 提供加入相关微信群的有效方式

### ISSUE THREAD

**Issue by EMUNES** [LearningOS/rust-based-os-comp2022#134]
很高兴能够认识到这个项目，结合报名要求来看，在报名阶段如何加入微信群呢。

**Is your feature request related to a problem? Please describe.**
根据秋冬季报名要求上写的，除了填报名的issue之外，还需要加入相关的微信群，但是微信群二维码是过期的，助教的微信也无法通过，所以加不了群。

**Describe the solution you'd like**
提供加入微信群的有效方法

**Describe alternatives you've considered**
更新微信群二维码

**Additional context**
也许说明一下微信群的作用会比较好，以及不开放人继续加群的话，大概的原因是什么，这样就不会导致想要报名的人频繁尝试加群但是加不了了。

**Comment by YdrMaster** [comment]
群就是交流用的，实时的比 github 快。今天再试试联系助教，不行晚上我给你弄

**Comment by EMUNES** [comment]
> 群就是交流用的，实时的比 github 快。今天再试试联系助教，不行晚上我给你弄

好的，今天试了到现在还是不行，能帮忙拉一下吗

**Comment by xchnotxzh** [comment]
> 

同求

**Comment by longguzzz** [comment]
人数看来会比较多，比较好的方式是更新二维码

xchnotxzh ***@***.***> 于2022年10月31日周一 18:48写道：

**Comment by YdrMaster** [comment]
@longguzzz 超过 200 人只能拉，二维码没用了

**Comment by YdrMaster** [comment]
@EMUNES @xchnotxzh 可以把你们微信号发我邮箱

**Comment by yrpang** [comment]
> @EMUNES @xchnotxzh 可以把你们微信号发我邮箱

您好我也已经发送了微信号到您邮箱，麻烦查收下，谢谢！

**Comment by YdrMaster** [comment]
我应该已经加了你们或者向你们的邮箱发了消息，如果没收到再叫我

**Comment by EMUNES** [comment]
> 我应该已经加了你们或者向你们的邮箱发了消息，如果没收到再叫我

好的，昨晚没注意到消息，我今早向您发送邮件了

**Comment by clingfei** [comment]
> 我应该已经加了你们或者向你们的邮箱发了消息，如果没收到再叫我

您好，我也发送了微信号到您的邮箱，麻烦您查收一下，谢谢！

**Comment by YdrMaster** [comment]
@clingfei 如果我没有加你，应该是我没收到，请重发一次（报名处也没查到你的信息）

**Comment by clingfei** [comment]
> Collaborator



> @clingfei 如果我没有加你，应该是我没收到，请重发一次（报名处也没查到你的信息）

已重发

**Comment by HaiQiu1998** [comment]
您好，已经将微信号发到您的邮箱，麻烦您拉一下，谢谢。

**Comment by xforcevesa** [comment]
怎么加群呀

**Comment by prime73num** [comment]
您好，已经将微信号发到您的邮箱，麻烦您拉一下，谢谢。

**Comment by YdrMaster** [comment]
@prime73num 加不上，不行发手机号

**Comment by zeract** [comment]
您好，已经将微信号发到您的邮箱，麻烦您拉一下，谢谢。
