### ISSUE TITLE
[Bug] rustlings自动评分部分并不能按照期望的“按题得分”

### ISSUE THREAD

**Issue by MoonOld** [LearningOS/rust-based-os-comp2022#136]
**Describe the bug**
autograding在跑到rustlings verify的时候因为后面的内容没有完成而编译错误，导致不能实现按题得分。

**To Reproduce**
1. 部分完成excercise
2. git add. && git commit -m "update" && git push

**Expected behavior**
得到部分分数

**Screenshots**
![图片](https://user-images.githubusercontent.com/47448870/199251195-3be447a0-737d-4030-9c28-8ae67e0cef22.png)

**Comment by IndifferentArea** [comment]
同上

**Comment by yfblock** [comment]
请采用新版的 `rustlings` [https://classroom.github.com/a/U37u3veU](https://classroom.github.com/a/U37u3veU).
