### ISSUE TITLE
[Bug] Lab0-0 CI不通过: 本地直接运行通过, push后无法通过检查

### ISSUE THREAD

**Issue by Comet959** [LearningOS/rust-based-os-comp2022#137]
**Describe the bug**
配置环境的实验: 未做代码改动, clone到本地可以正常运行make test1通过, push上去过后检查不通过.
**To Reproduce**

CI install步出错:
<img width="913" alt="Screen Shot 2022-11-01 at 22 37 10" src="https://user-images.githubusercontent.com/48466606/199259429-3e5c7ce6-ee1c-4d0b-a74e-bb2f86c9938f.png">

本地测试成功:
<img width="749" alt="Screen Shot 2022-11-01 at 22 38 26" src="https://user-images.githubusercontent.com/48466606/199259739-88f38c8e-7089-4000-a917-9536285d890e.png">

机型: MacBook M1

额外信息: 后面的实验可以正常执行, 并且可以正常CI通过, 只有lab0提交上去不行.

**Comment by YdrMaster** [comment]
截图有点少，看着像工具链版本问题，应该已经修复过了，更新仓库试试

**Comment by Comet959** [comment]
删除重建后可以了.
