### ISSUE TITLE
lab0-1：test2 GitHub Classroom Workflow 无法通过

### ISSUE THREAD

**Issue by IxaKylin** [LearningOS/rust-based-os-comp2022#27]
已经按步骤操作在os2目录按make run LOG=INFO ，并根目录 make setupclassroom_test2 提交到CI

可以看到这次提交是改动的，但就是没通过CI？ lab0-1：test2  应该还是设置环境的lab0来的吧？
[os2/src/link_app.S](https://github.com/LearningOS/lab0-1-run-os2-IxaKylin/commit/34852295e81a27080906289b923666c6eead0f79#diff-f978fae271057cfd31767d252bbae9569900c77fb4b97e2b24a2f89fb5117bbd)

![image](https://user-images.githubusercontent.com/100996593/177185288-4499ea1b-c0d0-42f5-a8b8-b09728912b81.png)

**Comment by myrfy001** [comment]
我已经解决了这个问题，可以参考#17
