### ISSUE TITLE
autograding.json没有被创建

### ISSUE THREAD

**Issue by CL-a11y** [LearningOS/rust-based-os-comp2022#5]
接受assignment邀请之后在仓库下执行make setupclassroom 会在.github/workflows中创建classroom.yml文件.    使用autograding功能还需要在.github/classroom文件夹下配置一个autograding.json.

ci出错截图
![屏幕截图 2022-06-28 210931](https://user-images.githubusercontent.com/105570623/176186702-fac7ca05-3c8c-43c4-8b5e-0cdb188ac76b.png)

**Comment by chyyuu** [comment]
谢谢！更新了项目根目录下的Makefile和Guide文档。对于后续的参加者，这个问题应该解决了。
