### ISSUE TITLE
有关于Rust圣经-Arc章节的一个问题

### ISSUE THREAD

**Issue by jackyliu16** [LearningOS/rust-based-os-comp2022#53]
想问的就是这个图片所指的代码，根据 https://course.rs/advance/smart-pointer/box.html 这个章节的描述，我想问下我能否理解成为这个部分就是相当于创建了一个Box指针，这个指针指向了s所对应的stack中的内存位置【1】
然而同时，这个box指针也存在于heap中，其所有权在开始时被a所有，因此**不能再将其所有权**赋值给另外一个对象，只能通过**`let b = a`**对于对象的所有权进行传递

那么我能不能通过这里的报错，简单的认为，box指针所指向的地址，必须是全局唯一的？
就是说不能通过多个box指针映射到同一个地址中

附上两段对应的图片：
![image](https://user-images.githubusercontent.com/50787361/178029248-b0063782-d1b2-4aa2-94c1-224beddf40d4.png)
![image](https://user-images.githubusercontent.com/50787361/178031260-64c75bf0-5c53-4361-a546-71c49cc0a155.png)

注：
[1].（s是String类型变量，存储于heap中，仅在stack中保存三个位置的数据，（pointer, capacity, length））
_[2]. heap中的每一个元素都被堆中的元素持有所有权？_
[3].https://course.rs/advance/smart-pointer/rc-arc.html

**Comment by jackyliu16** [comment]
这个是一个我的简单理解的图片
![75b63ddf6db6e5bb5b724217affbfc6](https://user-images.githubusercontent.com/50787361/178032050-c59aa066-f920-4c7e-a666-2d2394c1fb5f.jpg)

**Comment by werifu** [comment]
我来说说我的看法吧
Box这个智能指针的作用就只是表示：你想使用的数据（比如图1里就是一个String）会被存放在heap上，然后你*只能*通过Box这个指针来访问，因此实际上这个访问的指针本身是在stack上的，ownership也归这个智能指针所有，所以所谓不能有多个Box指向同一个heap地址是对的。（在不使用Rc/Arc的情况下）
但如何用多个Box去访问一个String呢，可以使用Box::new(&s)，引用是实现Copy的，我可以创建很多个，相当于存了几个值相同（都指向同一个String）的指针在heap上不同地方，由不同Box管理

**Comment by jackyliu16** [comment]
昂，理解了。就是说box这个智能指针实际上保存在栈中，而a和b两个元素不过是对于其的所有权转移是吗？


https://rustcc.cn/article?id=76e5f3fb-20b9-48c9-8fc6-a0aad40ced8c
