### ISSUE TITLE
执行Makefile文件 missing separator.  stop.

### ISSUE THREAD

**Issue by ZHOUSH41** [LearningOS/rust-based-os-comp2022#6]
按照实验要求执行 make setupclassroom_test1 时候，会报Makefile:74: *** missing separator.  Stop.，推测原因是  mkdir -p .github/workflows/ 这行会有Tab键，用空格键入就好

**Comment by ZHOUSH41** [comment]
test1~8的 mkdir -p .github/workflows/ 这行都会有这个问题

**Comment by chyyuu** [comment]
已合并PR#7 。@ZHOUSH41 谢谢！
