### ISSUE TITLE
一个关于lab提交的疑问

### ISSUE THREAD

**Issue by jackyliu16** [LearningOS/rust-based-os-comp2022#66]
想问下lab0-0-setup-env-run-os1以及lab0-1-setup-env-run-os1这两个仓库的最主要目的值在于让我们配置完成环境是么？

还有想问下lab0-0的这个仓库的具体提交要求是怎么样的呢？
这个仓库的配置过程如下
1. 事先已经完成rust环境，qemu环境配置
2. `git clone lab0-0`之后使用`make setupclassroom_test1`配置完成提交
3. 配置完成之后（理论上不是应该可以直接通过么）但是并没有通过，报错信息为
> Annotations
[deploy-doc](https://github.com/LearningOS/lab0-0-setup-env-run-os1-jackyliu16/runs/7278296695?check_suite_focus=true)
The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings.
> [Autograding](https://github.com/LearningOS/lab0-0-setup-env-run-os1-jackyliu16/runs/7278317102?check_suite_focus=true)
The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings.

但是这个地方似乎是仓库的问题？

**Comment by Andre-HJR** [comment]
建议 仓库设置为 `Public`

**Comment by jackyliu16** [comment]
设置为public之后重新提交，问题就解决了

**Comment by Ephmeral** [comment]
请问哪里可以设置public呢，这个classroom自动生成的仓库，和自己创建的不太一样，好像没有设置的选项

**Comment by jackyliu16** [comment]
> 请问哪里可以设置public呢，这个classroom自动生成的仓库，和自己创建的不太一样，好像没有设置的选项
@Ephmeral 
去群里面@助教，让他帮你改就可以了
