### ISSUE TITLE
《第一章：应用程序与基本执行环境》章《移除标准库依赖》节勘误

### ISSUE THREAD

**Issue by gdtdpt** [LearningOS/rust-based-os-comp2022#70]
[移除标准库依赖](https://learningos.github.io/rust-based-os-comp2022/chapter1/2remove-std.html#term-remove-std)小节，配置`os/.cargo/config`时应说明后续构建需要通过`rustup`在本地添加`riscv64gc-unknown-none-elf`的`target`才能在构建时自动应用此`target`
```sh
$ rustup target add riscv64gc-unknown-none-elf
```
---
[提供语义项 panic_handler](https://learningos.github.io/rust-based-os-comp2022/chapter1/2remove-std.html#panic-handler)小节，`panic_handler`配置在单独的文件`os/src/lang_items.rs`后，应说明在`os/src/main.rs`文件中添加以下内容才能正常建构
```rust
// os/src/main.rs
#![no_std]
mod lang_items;
// ... other code
```
---

[移除 main 函数](https://learningos.github.io/rust-based-os-comp2022/chapter1/2remove-std.html#main)小节最后给出的完整`main.rs`文件内容中包含了`panic_handler`内容，与上一小节独立文件编写`panic_handler`内容存在矛盾。

---
[分析被移除标准库的程序](https://learningos.github.io/rust-based-os-comp2022/chapter1/2remove-std.html#id2)小节中应说明`cargo-binutils 工具集`需要使用以下命令安装`llvm-tools-preview`才能正常使用
```sh
$ rustup component add llvm-tools-preview
```

**Comment by chyyuu** [comment]
@gdtdpt 已根据您的内容进行了更新 commit a2d28ab648dd68dac52e662c8f9c215777a0baa1 
谢谢！
