### ISSUE TITLE
《第一章：应用程序与基本执行环境》章《构建用户态执行环境》节勘误

### ISSUE THREAD

**Issue by gdtdpt** [LearningOS/rust-based-os-comp2022#71]
[实现输出字符串的相关函数](https://learningos.github.io/rust-based-os-comp2022/chapter1/3mini-rt-usrland.html#id7)小节中
1. 对`os/src/console.rs`文件内容说明时，`console.rs`文件代码使用到`core::fmt`模块中的`Result`、`Write`、`Arguments`，在文件开关应该声明`use core::fmt::{Result, Write, Arguments};`，后面`fmt::Arguments`和`fmt::Result`部分应替换为`Argument`和`Result`。
2. `os/src/console.rs`文件的代码中使用到了根模块`main.rs`文件中的`sys_write`方法，应说明在文件头部声明`use crate::sys_write;`

以下是我修改后的`console.rs`文件
```rust
//  os/src/console.rs
use core::fmt::{Write, Arguments, Result};
use crate::sys_write;

struct Stdout;

impl Write for Stdout {
    fn write_str(&mut self, s: &str) -> Result {
        sys_write(1, s.as_bytes());
        Ok(())
    }
}

pub fn print(args: Arguments) {
    Stdout.write_fmt(args).unwrap();
}

macro_rules! print {
    ($fmt: literal $(, $($arg: tt)+)?) => {
        $crate::console::print(format_args!($fmt $(, $($arg)+)?));
    }
}

macro_rules! println {
    ($fmt: literal $(, $($arg: tt)+)?) => {
        $crate::console::print(format_args!(concat!($fmt, "\n") $(, $($arg)+)?));
    }
}
```

**Comment by jackyliu16** [comment]
对的，我也注意到了相关问题，在[OSOTC2022构建用户态执行环境](https://learningos.github.io/rust-based-os-comp2022/chapter1/3mini-rt-usrland.html)中也出现了上述问题，之前还想发表评论，但是这个仓库不支持这个功能

按照OSOTC2022版本的需要添加如下操作 [ 我在这个地方只是提供了一个更轻松的解决方案 ]

```rust
use crate::sys_write;
use core::fmt;
use core::fmt::Write;
```

**Comment by chyyuu** [comment]
谢谢，已经更新！

> [实现输出字符串的相关函数](https://learningos.github.io/rust-based-os-comp2022/chapter1/3mini-rt-usrland.html#id7)小节中
> 
> 1. 对`os/src/console.rs`文件内容说明时，`console.rs`文件代码使用到`core::fmt`模块中的`Result`、`Write`、`Arguments`，在文件开关应该声明`use core::fmt::{Result, Write, Arguments};`，后面`fmt::Arguments`和`fmt::Result`部分应替换为`Argument`和`Result`。
> 2. `os/src/console.rs`文件的代码中使用到了根模块`main.rs`文件中的`sys_write`方法，应说明在文件头部声明`use crate::sys_write;`
> 
> 以下是我修改后的`console.rs`文件
> 
> ```rust
> //  os/src/console.rs
> use core::fmt::{Write, Arguments, Result};
> use crate::sys_write;
> 
> struct Stdout;
> 
> impl Write for Stdout {
>     fn write_str(&mut self, s: &str) -> Result {
>         sys_write(1, s.as_bytes());
>         Ok(())
>     }
> }
> 
> pub fn print(args: Arguments) {
>     Stdout.write_fmt(args).unwrap();
> }
> 
> macro_rules! print {
>     ($fmt: literal $(, $($arg: tt)+)?) => {
>         $crate::console::print(format_args!($fmt $(, $($arg)+)?));
>     }
> }
> 
> macro_rules! println {
>     ($fmt: literal $(, $($arg: tt)+)?) => {
>         $crate::console::print(format_args!(concat!($fmt, "\n") $(, $($arg)+)?));
>     }
> }
> ```
