### ISSUE TITLE
[Question] 在heap上创建和拷贝大数组有什么通常做法

### ISSUE THREAD

**Issue by alexfanqi** [LearningOS/rust-based-os-comp2022#83]
os3中要求统计每个task的系统调用次数，使用桶计数则每个task需要大小500的usize数组，内核stack只有4096大小，感觉应该分配到heap上。所以考虑用Box<[usize;500]>或者vec<usize>

但是发现Box<[usize;500]>我完全不知道怎么直接初始化，想先申请空间，再通过from_raw_parts.fill(0)，但是rust又要求array是必须初始化的。如果用vec.into_boxed_slice.try_into又和直接用vec没啥区别。

vec<usize>要拷贝给taskinfo就只能as_slice().try_into<[usize;500]>().unwrap()，但既然大小已知又肯定不需要动态大小，try_into检查就完全没有必要

我知道rust直接[0;large_num]是放在栈上会爆栈。想知道这种情况下rust初始化和拷贝 大数组有啥通常做法么，莫非unsafe

另外一个问题是为什么box<[T]>这样的slice box比box<[T;N]>这种放数组的box常见，找不到什么用数组box的地方

**Comment by Yakkhini** [comment]
我看到的几个解决办法（包括我自己）都是把这个定长数组放在 TaskBlockInner 里了，然后在任务管理的时候只切换别的内容（如上下文、逻辑空间、运行时间等）到下一个任务的字段，而不切换调用次数从而保证它的内容不变。其实这种设计不太好 [TaskInfo 的语义缺陷](http://localhost:3000/#/computerSci/20220706-zcore?id=taskinfo-%e5%ae%9e%e7%8e%b0%e7%9a%84%e8%af%ad%e4%b9%89%e7%bc%ba%e9%99%b7)，因为这代表着调用次数数组作为一个任务管理器中应唯一存在的数据组被初始化在了每一个任务的内部块中。但是要在系统内核里申请这样一块空间实在有点麻烦。后面的章节里好像提到过实现了一个什么东西来让我们在内核空间里使用 vec 向量，但我没有仔细看。另外一方面，你也可以针对每一个任务块的内部空间中单独声明一个调用次数数组，然后在之后的解析中遍历每一个任务并将其相加，不过这也增加了一些工作量。总之，至少在 os3 阶段，想要比较方便地创建一个可变数组并在内核中访问，TaskBlockInner 是一个比较方便虽然不太完美的选择。这是一种妥协。

**Comment by alexfanqi** [comment]
等下，我好像理解错了任务要求，是要统计系统全局调用数总和，还是每个task分别的系统调用数目？

因为看到有heap_alloc.rs文件是个初始化buddy heap alloc的，所以heap应该就能拿来直接用，没有heap，refcell应该也是用不成的

**Comment by alexfanqi** [comment]
哦，nm看了下，果然appmanger是在bss段的。vec!和box!也是果然用不成。那就只能放appmanager里了

**Comment by Yakkhini** [comment]
是我理解错了，这个好像就是统计每个单独的任务中系统调用次数。不过怎么实现应该也没差，因为它的测例中就是只控制了询问结果应该大于某个值而不是小于某个值，而且也只有一个测例与 TaskInfo 有关。那就没问题了，用不了 vec! 正好把[u8; 500] 放在任务控制块里
