### ISSUE TITLE
[Bug] os6-ref 下执行 make run 触发panic

### ISSUE THREAD

**Issue by zhaiqiming** [LearningOS/rust-based-os-comp2022#84]
请问各位老师，如下情况是否符合实验代码的预期：

未进行任何修改的前提下，在os6-ref、os7-ref、os8-ref目录下执行make run，每次执行必现panic
在Github CodeSpace 或 本机（MacOS Intel Core），都出现以上问题

![image](https://user-images.githubusercontent.com/25913700/179999723-acb540e6-69c4-4a2a-ba54-07f2d59218d7.png)

其他同学也有出现这种情况：
![image](https://user-images.githubusercontent.com/25913700/179999924-32082662-c390-4f37-ab06-597577357eee.png)

**Comment by zhaiqiming** [comment]
tips：如果你也遇到以上问题，无法通过交互式shell加载进程进行测试。 一个临时的办法是通过 make test* 直接进行测试， 在执行make test* 时亲测并无异常

**Comment by chyyuu** [comment]
谢谢你发现的问题！

已经修复了这个问题。commit id 是 [70ae28a](https://github.com/LearningOS/rust-based-os-comp2022/commit/70ae28ab2280f3e57d14b7a631e7508fe5b4bbaf)

> 请问各位老师，如下情况是否符合实验代码的预期：
> 
> 未进行任何修改的前提下，在os6-ref、os7-ref、os8-ref目录下执行make run，每次执行必现panic 在Github CodeSpace 或 本机（MacOS Intel Core），都出现以上问题
> 
> ![image](https://user-images.githubusercontent.com/25913700/179999723-acb540e6-69c4-4a2a-ba54-07f2d59218d7.png)
> 
> 其他同学也有出现这种情况： ![image](https://user-images.githubusercontent.com/25913700/179999924-32082662-c390-4f37-ab06-597577357eee.png)
