### ISSUE TITLE
[Question] 请问relatedinfo.md内的视频密码可以提供吗？

### ISSUE THREAD

**Issue by sunwenming** [LearningOS/rust-based-os-comp2022#90]
**Describe the question**
请问relatedinfo.md内的视频密码可以提供吗？
https://github.com/LearningOS/rust-based-os-comp2022/blob/main/relatedinfo.md#课程视频

**Comment by xuwuu** [comment]
时间后四位

**Comment by xuwuu** [comment]
> **Describe the question** 请问relatedinfo.md内的视频密码可以提供吗？ [https://github.com/LearningOS/rust-based-os-comp2022/blob/main/relatedinfo.md#课程视频](https://github.com/LearningOS/rust-based-os-comp2022/blob/main/relatedinfo.md#%E8%AF%BE%E7%A8%8B%E8%A7%86%E9%A2%91)

时间后四位
