### ISSUE TITLE
[Question] 为什么CI跑到Run actions-rs/install@v0.1失败了

### ISSUE THREAD

**Issue by pjzhong** [LearningOS/rust-based-os-comp2022#96]
有同学遇到这种情况吗，除了os5文件的内容之外，其它都没改动过。

[报错CI](https://github.com/LearningOS/lab3-os5-pjzhong/runs/7729941850?check_suite_focus=true)

**Comment by wq-yang** [comment]
编译 libc 需要 rust 版本 >=1.62.0. https://github.com/rust-lang/libc#rust-version-support
可以改 GitHub Actions 和 项目的 toolchain 版本解决

**Comment by pjzhong** [comment]
> 编译 libc 需要 rust 版本 >=1.62.0. https://github.com/rust-lang/libc#rust-version-support 可以改 GitHub Actions 和 项目的 toolchain 版本解决

感谢，这个方法可以
